Controllers/ColleaguesController.cs
using App.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace App.Controllers;

public class ColleaguesController : Controller
{
    readonly UserManager<MyIdentityUser> userManager;
    readonly Account_Process accountProcess;
    public ColleaguesController(UserManager<MyIdentityUser> userManager, Account_Process accountProcess)
    {
        this.userManager = userManager;
        this.accountProcess = accountProcess;
    }

    public async Task<IActionResult> Index(string? branch, int page = 1)
    {
        List<MyIdentityUser> allSelectedUsers;
        if (branch == null)
        {
            allSelectedUsers = await userManager.Users.ToListAsync();
        }
        else
        {
            allSelectedUsers = await userManager.Users
                .Where(u => u.Branch == branch)
                .ToListAsync();
        }

        if (allSelectedUsers.Any(u => u.UserGuid == "admin"))
        {
            allSelectedUsers.Remove(allSelectedUsers.Single(u => u.UserGuid == "admin"));
        }

        var orderedUsers = accountProcess.OrderUsersByPost(allSelectedUsers);

        //***** sorts 10 colleagues per page *****
        ViewBag.LastPage = (int)Math.Ceiling(orderedUsers.Count / 10.0);
        var usersList = orderedUsers.Skip((page - 1) * 10).Take(10).ToList();

        return View(usersList);
    }
}

Controllers/OrdersController.cs
using System.Globalization;
using App.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace App.Controllers;

[Authorize]
[AutoValidateAntiforgeryToken]
public class OrdersController : Controller
{
    readonly Orders_DbContext ordersDb;
    readonly UserManager<MyIdentityUser> userManager;
    readonly PersianDateProcess persianDateProcess;
    readonly Assessment_DbContext assessmentDb;
    readonly Orders_Process ordersProcess;
    readonly IConfiguration configuration;
    readonly Notification_Process notification_Process;
    readonly int NumberOfElementsPerPage = 3;
    public OrdersController(Orders_DbContext ordersDb, UserManager<MyIdentityUser> userManager,
    PersianDateProcess persianDateProcess, Assessment_DbContext assessmentDb, Orders_Process ordersProcess,
    IConfiguration configuration, Notification_Process notification_Process)
    {
        this.ordersDb = ordersDb;
        this.userManager = userManager;
        this.persianDateProcess = persianDateProcess;
        this.assessmentDb = assessmentDb;
        this.ordersProcess = ordersProcess;
        this.configuration = configuration;
        this.notification_Process = notification_Process;
    }

    public async Task<IActionResult> Index(string? Branch = null,
    string? FromDate = null, string? ToDate = null, int page = 1)
    {
        MyIdentityUser me = (await userManager.FindByNameAsync(User.Identity!.Name!))!;
        MyIdentityUser? registrar = null;

        persianDateProcess.TryConvertToDateTime(FromDate, out DateTime? FromDateTime);
        FromDateTime ??= DateTime.Today - TimeSpan.FromDays(30);
        persianDateProcess.TryConvertToDateTime(ToDate, out DateTime? ToDateTime);
        if (ToDateTime != null) ToDateTime = ToDateTime.Value.AddHours(23).AddMinutes(59);

        if (me.UserGuid == "admin")
        {
            registrar = null;
        }
        else if (await userManager.IsInRoleAsync(me, "Order_Registrars"))
        {
            registrar = me;
        }
        else if (!await userManager.IsInRoleAsync(me, "Can_Watch_Orders"))
        {
            Branch = me.Branch;
        }

        string commaSeparatedBranch = "," + Branch + ",";
        Orders_IndexModel indexModel = new()
        {
            Branch = Branch,
            Registrar = registrar,
            FromDate = FromDateTime.Value.ToString("yyyy/MM/dd", new CultureInfo("fa-IR")),
            ToDate = ToDate,
            Orders = await ordersDb.Orders
                .Where(o => (registrar == null || o.RegistrarGuid == registrar.UserGuid) &&
                    (Branch == null || o.BranchesCommaSeparated.Contains(commaSeparatedBranch)) &&
                    o.RegisterDate >= FromDateTime.Value &&
                    (ToDateTime == null || o.RegisterDate <= ToDateTime))
                .OrderByDescending(o => o.RegisterDate)
                .ToListAsync(),
            //.Where(o => Branch == null || o.Branches.Contains(Branch))
            //.ToList(),
        };

        if (Branch != null)
        {
            indexModel.OrderGuidRespondDates = [];
            foreach (Orders_DbModel order in indexModel.Orders)
            {
                var performances = await assessmentDb.Performances
                .Where(p => p.RegisterDate != null && p.Branch == Branch && p.OrderGuid == order.Guid)
                .ToListAsync();

                if (performances.Count > 0)
                {
                    indexModel.OrderGuidRespondDates[order.Guid] = performances
                    .OrderByDescending(p => p.RegisterDate!.Value)
                    .Select(p => p.RegisterDate!.Value)
                    .First();
                }
            }
        }

        //review notifs
        var allOrderGuids = indexModel.Orders.Select(o => o.Guid);
        for (int i = 0; i < me.Notifications.Count; i++)
        {
            string notifString = me.Notifications[i];
            if (notifString.Contains("order_"))
            {
                string orderGuid = notifString.Replace("order_", "");
                if (!allOrderGuids.Contains(orderGuid))
                {
                    await notification_Process.RemoveNotif_FromUser(notifString, me);
                    i--;
                }
            }
        }

        ViewBag.LastPage = (int)Math.Ceiling(indexModel.Orders.Count / (double)NumberOfElementsPerPage);

        indexModel.Orders = indexModel.Orders
        .Skip((page - 1) * NumberOfElementsPerPage)
        .Take(NumberOfElementsPerPage)
        .ToList();

        return View("List", indexModel);
    }

    public async Task<IActionResult> Open(string orderGuid)
    {
        Orders_DbModel? orderDbModel = await ordersDb.Orders.FirstOrDefaultAsync(o => o.Guid == orderGuid);
        if (orderDbModel is null)
        {
            object o = $"درخواست پیدا نشد!";
            ViewBag.ResultState = "danger";
            return View("Result", o);
        }

        MyIdentityUser me = (await userManager.FindByNameAsync(User.Identity!.Name!))!;
        if (await userManager.IsInRoleAsync(me, "Can_Watch_Orders") ||
            orderDbModel.Branches.Contains(me.Branch) ||
            me.UserGuid == orderDbModel.RegistrarGuid)
        {

            Orders_OpenModel openModel = new()
            {
                Deadline = orderDbModel.Deadline,
                Description = orderDbModel.Description,
                Guid = orderDbModel.Guid,
                MeOpener = me,
                PerformanceField = orderDbModel.PerformanceField,
                PerformanceType = orderDbModel.PerformanceType,
                RegisterDate = orderDbModel.RegisterDate,
                Registrar = await userManager.Users.FirstOrDefaultAsync(u => u.UserGuid == orderDbModel.RegistrarGuid),
                Subject = orderDbModel.Subject,
            };
            foreach (string branch in orderDbModel.Branches)
            {
                var performances = await assessmentDb.Performances
                .Include(p => p.ExpertConsiderations)
                .Where(p => p.Branch == branch &&
                    p.OrderGuid == orderDbModel.Guid)
                .ToListAsync();
                openModel.BranchPerformances.Add(branch, performances);
            }

            //remove notif
            await notification_Process.RemoveNotif_FromUser($"order_{orderDbModel.Guid}", me);

            return View(openModel);
        }

        object o1 = "شما مجاز به مشاهده این درخواست نمیباشید!";
        ViewBag.ResultState = "danger";
        return View("Result", o1);
    }

    [Authorize(Roles = "Order_Registrars")]
    public async Task<IActionResult> NewOrder()
    {
        MyIdentityUser me = (await userManager.FindByNameAsync(User.Identity!.Name!))!;
        Orders_FormModel formModel = new();
        ViewBag.MeFullName = me.FullName;
        return View("Form", formModel);
    }

    [Authorize(Roles = "Order_Registrars")]
    public async Task<IActionResult> SubmitNewOrder(Orders_FormModel formModel)
    {
        if (ModelState.IsValid)
        {
            MyIdentityUser meSubmitter = (await userManager.FindByNameAsync(User.Identity!.Name!))!;
            persianDateProcess.TryConvertToDateTime(formModel.Deadline, out DateTime? deadlineDateTime);
            if (deadlineDateTime is null)
            {
                ModelState.AddModelError("تاریخ", "مهلت انجام درخواست نادرست میباشد!");
                return View("Form", formModel);
            }
            deadlineDateTime = deadlineDateTime.Value.AddHours(23).AddMinutes(59);

            if (formModel.Branches.Length == 0)
            {
                ModelState.AddModelError("اداره ها", "حداقل یک اداره باید انتخاب شود!");
                return View("Form", formModel);
            }

            Orders_DbModel orderDbModel = new()
            {
                Branches = formModel.Branches.ToList(),
                Deadline = deadlineDateTime.Value,
                Description = formModel.Description,
                //Guid
                PerformanceField = formModel.PerformanceField,
                PerformanceType = formModel.PerformanceType,
                RegisterDate = DateTime.Now,
                RegistrarGuid = meSubmitter.UserGuid,
                Subject = formModel.Subject,
            };

            await ordersDb.Orders.AddAsync(orderDbModel);
            await ordersDb.SaveChangesAsync();

            //seed
            await ordersProcess.UpdateOrderSeed(orderDbModel);

            //notification
            foreach (MyIdentityUser user in await userManager.Users.Where(u => orderDbModel.Branches.Contains(u.Branch)).ToListAsync())
            {
                await notification_Process.SetNewNotif_ToUser($"order_{orderDbModel.Guid}", user);
            }

            //delete old orders
            await ordersProcess.RemoveOlderOrders(30);//30 days after deadline

            return RedirectToAction(nameof(Index));
        }
        return View("Form", formModel);
    }

    [Authorize(Roles = "Can_Watch_Orders")]
    public async Task<IActionResult> ReportPerformances(string? FromDate = null, string? ToDate = null)
    {
        persianDateProcess.TryConvertToDateTime(FromDate, out DateTime? FromDateTime);
        FromDateTime ??= DateTime.Today - TimeSpan.FromDays(30);
        persianDateProcess.TryConvertToDateTime(ToDate, out DateTime? ToDateTime);
        if (ToDateTime != null) ToDateTime = ToDateTime.Value.AddHours(23).AddMinutes(59);

        Orders_ReportModel reportModel = new()
        {
            FromDate = FromDateTime.Value.ToString("yyyy/MM/dd", new CultureInfo("fa-IR")),
            ToDate = ToDate,
            Orders = await ordersDb.Orders
                .Where(o => o.RegisterDate >= FromDateTime &&
                    (ToDateTime == null || o.RegisterDate <= ToDateTime))
                .OrderByDescending(o => o.RegisterDate)

Views/Shared/Components/NavBarComponent/Default.cshtml
@model MyIdentityUser?
@{
    bool newMessagesNotif = Model is not null && Model.Notifications.Any(n => n.Contains("msg_"));
    bool newPerformanceNotif = Model is not null && Model.Notifications.Any(n => n.Contains("perf_"));
    bool newOrderNotif = Model is not null && Model.Notifications.Any(n => n.Contains("order_"));
    bool accountBell = newMessagesNotif || newPerformanceNotif || newOrderNotif;
    var configuration = Context.RequestServices.GetRequiredService<IConfiguration>();
    var currentUrl = Context.Request.GetEncodedUrl();
    ViewBag.AllRelatedUsers = ViewBag.AllRelatedUsers ?? new List<MyIdentityUser>();
}
<!---------------------------------------------------------->
<!--------------------------------------- header ------------------------------------------->

<div id="headerbce54a4e200b47f4a58283a8dd4f75b2" class="header clearfix">
    <style>
        #headerbce54a4e200b47f4a58283a8dd4f75b2 {
            background-color: rgb(36, 36, 102);
            /*height: 100px;*/
            /*position: absolute;
                left: 0;*/
            width: 100%;

        }

        #headerbce54a4e200b47f4a58283a8dd4f75b2 img {
            float: left;
        }
    </style>
    <img asp-append-version="true" src="/Images/iran-flag.png" alt="" style="width: 150px;">
    <img asp-append-version="true" src="/Images/logo.png" alt=""
        style="height: 80px;width: 100px;background-color: white;
            float: right;margin-left: 10px; margin-right: 3px; border: 1px solid gray;margin-top: 3px;background-color: transparent;">
    <img asp-append-version="true" src="/Images/shoar1403.png" alt="" style="margin-left: 10px;margin-top: 5px;">

    <!---------------------------------------  ------------------------------------------->
    <style>
        #central-office-p {
            color: white;
            using Microsoft.AspNetCore.Http.Extensions;
            using Microsoft.AspNetCore.Http.Extensions;
            font-size: 24px;
            position: absolute;
            left: 50vw;
            transform: translateX(-50%);
            top: 0px;
            width: fit-content;
            /*background-color: rgb(36, 36, 102);
            margin: 30px 0 0 0;
            padding: 0;*/
        }

        @@media screen and (max-width:1200px) {
            #central-office-p {
                top: -20px;
            }
        }

        @@media screen and (max-width:800px) {
            #central-office-p {
                left: 65vw;
            }
        }

        @@media screen and (max-width:600px) {
            #central-office-p {
                left: 50vw;
                top: 60px;
            }
        }
    </style>
    <p id="central-office-p" class="iran-nastaliq">@configuration["NavBarTitle"]</p>
    <!--------------------------------------- main menu ------------------------------------------->

    <div class="mainmenu clearfix">
        <style>
            #headerbce54a4e200b47f4a58283a8dd4f75b2 .mainmenu {
                /*background-color: #cfcfcf;*/
                width: fit-content;
                float: right;
                /*border: 1px solid gray;*/
            }
        </style>


        <style>
            .af087666d9a3a44c0af4059baa12e712a {
                background-color: rgba(0, 0, 0, 0);
                border: none;
                color: white;
                padding: 16px;
                /*15px 32px;*/
                text-align: center;
                text-decoration: none;
                display: block;
                font-size: 16px;
                /*margin: 4px 2px;*/
                cursor: pointer;
                float: right;
                margin: 30px 1px 0;
            }

            .af087666d9a3a44c0af4059baa12e712a:hover {
                background-color: #3e8e41;
            }
        </style>
        <a asp-controller="Home" asp-action="Index" class="af087666d9a3a44c0af4059baa12e712a">
            خانه
        </a>

        <style>
            .dropdown920b9a8f2556431397c7c19e2a4d4418 {
                position: relative;
                display: inline-block;
                margin: 30px 1px 0;
            }

            .dropdown920b9a8f2556431397c7c19e2a4d4418 .dropbtn {
                background-color: rgba(0, 0, 0, 0);
                color: white;
                padding: 16px;
                font-size: 16px;
                border: none;
                /*cursor: pointer;*/
                display: block;
                text-decoration: none;
            }

            .dropdown920b9a8f2556431397c7c19e2a4d4418 .dropdown-content {
                display: none;
                position: absolute;
                background-color: #f9f9f9;
                min-width: 160px;
                max-width: 350px;
                width: fit-content;
                box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
                z-index: 1;
            }

            .dropdown920b9a8f2556431397c7c19e2a4d4418 .dropdown-content a {
                color: black;
                padding: 12px 16px;
                text-decoration: none;
                display: block;
            }

            .dropdown920b9a8f2556431397c7c19e2a4d4418 .dropdown-content a:hover {
                background-color: #cfcfcf
            }

            .dropdown920b9a8f2556431397c7c19e2a4d4418:hover .dropdown-content {
                display: block;
            }

            .dropdown920b9a8f2556431397c7c19e2a4d4418:hover .dropbtn {
                background-color: #3e8e41;
            }
        </style>
        @if (configuration["ServiceActivity:Colleagues"] == "true")
        {
            <div class="dropdown920b9a8f2556431397c7c19e2a4d4418" style="float: right;">
                <a asp-controller="Colleagues" asp-action="Index" class="dropbtn">همکاران</a>
                <div class="dropdown-content" style="right: 0;max-height: calc(100vh - 100px);overflow:auto;">
                    @foreach (string branch in configuration.GetSection("AllBranches").Get<List<string>>() ?? [])
                    {
                        <a asp-controller="Colleagues" asp-action="Index" asp-route-branch="@branch">@branch</a>
                    }
                </div>
            </div>
        }
        @if (configuration["ServiceActivity:Regulations"] == "true")
        {
            <div class="dropdown920b9a8f2556431397c7c19e2a4d4418" style="float: right;">
                <a asp-controller="Regulations" asp-action="Index" class="dropbtn">دستورالعمل ها</a>
                <div class="dropdown-content" style="right: 0;">
                    @foreach (string category in ViewBag.RegulationCategories ?? Enumerable.Empty<string>())
                    {
                        <a asp-controller="Regulations" asp-action="Index" asp-route-category="@category">@category</a>
                    }
                </div>
            </div>
        }
        @if (configuration["ServiceActivity:Downloads"] == "true")
        {
            <div class="dropdown920b9a8f2556431397c7c19e2a4d4418" style="float: right;">
                <a asp-controller="Downloads" asp-action="Index" class="dropbtn">دانلودها</a>
                <div class="dropdown-content" style="right: 0;">
                    @foreach (string category in ViewBag.DownloadCategories ?? Enumerable.Empty<string>())
                    {
                        <a asp-controller="Downloads" asp-action="Index" asp-route-category="@category">@category</a>
                    }
                </div>
            </div>
        }


    </div>
    @if (User.Identity == null || !User.Identity.IsAuthenticated)
    {
        <a asp-controller="Account" asp-action="Login" class="af087666d9a3a44c0af4059baa12e712a" style="float: left;">
            ورود
        </a>
    }
    else
    {
        <div class="dropdown920b9a8f2556431397c7c19e2a4d4418" style="float: left;">
            <img class="profile-img" src="/Account/ClientImage?username=@(Model?.UserName)&v=@(Model?.Version)" alt=""
                style="width: 50px;height:50px;border-radius:50%;float:right;">
            <button class="dropbtn" style="position: relative;">
                @Model?.FullName
                @if (accountBell)
                {
                    <span style="display: block;color:red;position:absolute;top:0;left:0;font-size: 14px;">
                        &starf;
                    </span>
                }
            </button>
            <div class="dropdown-content" style="right: 0;max-height: calc(100vh - 100px);overflow:auto;">
                @if (((List<MyIdentityUser>)ViewBag.AllRelatedUsers).Count > 0)
                {
                    string currentBranchPost = $"{Model?.Branch}_{Model?.Post}";
                    @foreach (MyIdentityUser relatedUser in ViewBag.AllRelatedUsers)
                    {
                        string bp = $"{relatedUser.Branch}_{relatedUser.Post}";
                        @if (currentBranchPost == bp)
                        {
                            <a style="background-color: lawngreen;font-size:14px;text-wrap: nowrap;">
                                <input type="radio" checked />
                                @bp
                            </a>
                        }
                        else
                        {
                            <a style="font-size:14px;text-wrap: nowrap;" asp-controller="Account" asp-action="SwitchSubUser"
                                asp-route-userGuid="@relatedUser.UserGuid" asp-route-returnUrl="@currentUrl">
                                <input type="radio" style="cursor: pointer;" onclick="this.parentElement.click();" />
                                @bp
                            </a>

                        }
                    }
                }
                <a asp-controller="Account" asp-action="Profile">پروفایل</a>
                @if (configuration["ServiceActivity:Messages"] == "true")
                {
                    <a asp-controller="Messages" asp-action="Index" style="position: relative;">
                        پیامها
                        @if (newMessagesNotif)
                        {
                            <span style="display: block;color:red;position:absolute;top:10px;left:10px;">
                                &starf;
                            </span>
                        }
                    </a>
                }
                <a asp-controller="Assessment" asp-action="Index" style="position: relative;">
                    عملکردها
                    @if (newPerformanceNotif)
                    {
                        <span style="display: block;color:red;position:absolute;top:10px;left:10px;">
                            &starf;
                        </span>
                    }
                </a>

                <a asp-controller="Orders" asp-action="Index" style="position: relative;">
                    درخواست ها
                    @if (newOrderNotif)
                    {
                        <span style="display: block;color:red;position:absolute;top:10px;left:10px;">
                            &starf;
                        </span>
                    }
                </a>
                <!--a asp-controller="Orders" asp-action="ReportPerformances" style="position: relative;">
                                                    گزارش عملکرد همه توابع به درخواست ها
                                                </a-->
                <a asp-controller="Assessment" asp-action="ScoreList">سوابق و امتیازات</a>
                @if (User.IsInRole("Account_Admins"))
                {
                    <a asp-controller="Account" asp-action="UsersList">کاربران</a>
                    <a asp-controller="Account" asp-action="RolesList">دسترسی ها</a>
                }
                @if (User.Identity.Name == "admin")
                {
                    <a asp-controller="AppAdministration" asp-action="Backup">بکاپ</a>
                }

                <a asp-controller="Account" asp-action="Logout">خروج</a>
            </div>
        </div>
    }

</div>